DROP TABLE TCITIZEN IF EXISTS;
DROP TABLE AGENT IF EXISTS;

CREATE TABLE IF NOT EXISTS AGENT (
	id BIGINT PRIMARY KEY,
	identificador VARCHAR(50) UNIQUE NOT NULL,--nombre de usuario y único
	contrasena VARCHAR(30) NOT NULL,
	nombre VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	localizacion VARCHAR(50),
	tipo VARCHAR(50) NOT NULL,
	--tipoCodigo INT NOT NULL
);

